# Generated by Django 4.2.10 on 2024-02-17 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='profile/user-placeholder.png', force_format='WEBP', keep_meta=False, null=True, quality=80, scale=None, size=[200, 200], upload_to='media/profile/')),
                ('cover', django_resized.forms.ResizedImageField(crop=None, default='profile/user-placeholder.png', force_format='WEBP', keep_meta=False, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='media/profile/covers/')),
                ('is_moderator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
