# Generated by Django 3.1.1 on 2020-09-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=75, verbose_name='Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Studio Name')),
                ('founded', models.DateField(verbose_name='Year of Foundation')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Anime Name')),
                ('episodes_number', models.IntegerField(verbose_name='Number of Episodes')),
                ('minutes_per_episode', models.IntegerField(verbose_name='Minutes per Episode')),
                ('sinopse', models.TextField(max_length=800, verbose_name='Sinopse')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studio', verbose_name='Studio')),
            ],
        ),
    ]
