# Generated by Django 3.1.1 on 2020-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200912_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='categorie',
        ),
        migrations.AddField(
            model_name='anime',
            name='categorie',
            field=models.ManyToManyField(to='api.Categorie', verbose_name='Categorie'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(to='api.Studio', verbose_name='Studio'),
        ),
    ]
