# Generated by Django 3.1.1 on 2020-09-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200915_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=75, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Licensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Studio Name')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Studio Name')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=150, verbose_name='Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150, verbose_name='Source')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='aired',
            field=models.DateField(null=True, verbose_name='Aired'),
        ),
        migrations.AddField(
            model_name='anime',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='categorie',
            field=models.ManyToManyField(to='api.Categorie', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sinopse',
            field=models.TextField(max_length=800, verbose_name='Synopsis'),
        ),
        migrations.AddField(
            model_name='anime',
            name='alternative_title',
            field=models.ManyToManyField(to='api.AlternativeTitle', verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='anime',
            name='licensors',
            field=models.ManyToManyField(blank=True, to='api.Licensor', verbose_name='Licensors'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producers',
            field=models.ManyToManyField(to='api.Producer', verbose_name='Producers'),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rating', verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.animetype', verbose_name='Anime'),
        ),
    ]
