# Generated by Django 3.1.1 on 2020-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200915_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='alternative_title',
            field=models.ManyToManyField(to='api.AlternativeTitle', verbose_name='Alternative Title'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='founded',
            field=models.DateField(blank=True, null=True, verbose_name='Year of Foundation'),
        ),
    ]
