# Generated by Django 3.1.1 on 2020-09-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200916_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='animerewatched',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='aired',
            field=models.DateField(blank=True, null=True, verbose_name='Aired'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='alternative_title',
            field=models.ManyToManyField(blank=True, to='api.AlternativeTitle', verbose_name='Alternative Title'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='api.Categorie', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Episodes'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='minutes_per_episode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutes per Episode'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='producers',
            field=models.ManyToManyField(blank=True, to='api.Producer', verbose_name='Producers'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rating', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sinopse',
            field=models.TextField(blank=True, max_length=800, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(blank=True, to='api.Studio', verbose_name='Studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.animetype', verbose_name='Type'),
        ),
    ]
