# Generated by Django 3.1.1 on 2020-09-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200917_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_number', models.IntegerField(null=True, verbose_name='Number of Episodes')),
                ('completed', models.IntegerField(verbose_name='How many times completed?')),
                ('score', models.IntegerField(null=True, verbose_name='Score')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime', verbose_name='Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(verbose_name='Value')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='animewatching',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='animewatching',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnimeRewatched',
        ),
        migrations.DeleteModel(
            name='AnimeWatching',
        ),
        migrations.AddField(
            model_name='animestatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='animestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
