# Generated by Django 3.1.1 on 2020-11-02 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150, verbose_name='Date Option')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75, verbose_name='Characters')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='profile/user-placeholder.png', force_format='JPEG', keep_meta=False, null=True, quality=80, size=[200, 200], upload_to='avatar')),
            ],
        ),
        migrations.AddField(
            model_name='animestatus',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile/user-placeholder.png', force_format='JPEG', keep_meta=False, null=True, quality=80, size=[200, 200], upload_to='media/profile/'),
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, null=True, quality=80, size=[800, 600], upload_to='custom_list')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCustomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anime', verbose_name='Anime')),
                ('custom_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customlist', verbose_name='CustomList')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='date_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dateoption', verbose_name='Date Option(Aired)'),
        ),
    ]
