# Generated by Django 3.1.1 on 2020-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_animereview_topic_topiccategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trailer(Youtube ID)'),
        ),
    ]
