# Generated by Django 3.1.1 on 2020-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_anime_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='animereview',
            name='draft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
