# Generated by Django 3.1.1 on 2020-11-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_animereview_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='animereview',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.animestatus', verbose_name='Status'),
        ),
    ]
