# Generated by Django 3.1.1 on 2020-11-19 11:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_animereview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, null=True, quality=80, size=[800, 600], upload_to='anime_cover'),
        ),
    ]
