# Generated by Django 3.1.1 on 2021-01-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201221_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150, verbose_name='Source')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='stream_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.streamsource', verbose_name='Stream Source'),
        ),
    ]
