# Generated by Django 3.1.1 on 2021-02-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210105_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='animestatus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(to='api.Categorie'),
        ),
    ]
