# Generated by Django 3.1.1 on 2021-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210208_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animestatus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
