# Generated by Django 3.1.1 on 2021-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210209_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animestatus',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
