# Generated by Django 3.1.1 on 2021-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210305_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='api.Categorie'),
        ),
    ]
