# Generated by Django 3.0.4 on 2021-07-12 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_auto_20210312_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(verbose_name='Valor do Nível')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='ReportMotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=100, verbose_name='Motive')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(verbose_name='Valor Numérico')),
                ('status', models.CharField(max_length=75, verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='blockuser',
            field=models.ManyToManyField(related_name='blockuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=None, default='profile/user-placeholder.png', force_format='JPEG', keep_meta=False, null=True, quality=80, size=[1920, 1080], upload_to='media/profile/covers/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.ManyToManyField(to='api.Rating'),
        ),
        migrations.AlterField(
            model_name='customlist',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, null=True, quality=80, size=[1920, 1080], upload_to='custom_list'),
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('pid', models.CharField(max_length=100, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ReportMotive', verbose_name='Motive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=360, verbose_name='Question')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=80, size=[1920, 1080], upload_to='quizz')),
                ('date_create', models.DateField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Anime', verbose_name='Anime')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.QuizzLevel', verbose_name='Level')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserContentStatus', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
